# Generated by Django 4.0.2 on 2022-02-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recordapp', '0003_openfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='open_folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_folder', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('Opened_date', models.DateTimeField(auto_now_add=True)),
                ('Closed_date', models.DateTimeField()),
                ('patient_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info')),
            ],
        ),
    ]
