# Generated by Django 4.0.2 on 2022-02-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_folderapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='open_folder',
            name='Closed_date',
        ),
        migrations.RemoveField(
            model_name='open_folder',
            name='timestamp',
        ),
    ]
