# Generated by Django 4.0.2 on 2022-07-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_folderapp', '0002_remove_open_folder_closed_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='open_folder',
            old_name='patient_folder',
            new_name='patient_infor',
        ),
    ]
