# Generated by Django 4.0.2 on 2022-07-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_folderapp', '0003_rename_patient_folder_open_folder_patient_infor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='open_folder',
            old_name='patient_infor',
            new_name='patient_info',
        ),
        migrations.AlterField(
            model_name='open_folder',
            name='Opened_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
