# Generated by Django 4.0.1 on 2022-01-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_info',
            old_name='othernames',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='patient_info',
            old_name='surname',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='patient_info',
            name='mname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
