# Generated by Django 4.0.1 on 2022-02-05 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0002_rename_othernames_patient_info_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openfolder', models.BooleanField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info')),
            ],
        ),
    ]
