# Generated by Django 4.0.2 on 2022-06-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0003_openfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_info',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('CIV', 'Civillian'), ('Pesonnel', 'Personnel')], max_length=10),
        ),
        migrations.AddField(
            model_name='patient_info',
            name='status',
            field=models.CharField(blank=True, choices=[('NHIS', 'NHIS'), ('Not NHIS', 'Not NHIS')], max_length=10),
        ),
        migrations.CreateModel(
            name='nhisdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmoname', models.CharField(blank=True, max_length=120, null=True)),
                ('hmophone', models.CharField(blank=True, max_length=120, null=True)),
                ('hmoaddress', models.CharField(blank=True, max_length=120, null=True)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info')),
            ],
        ),
    ]
