# Generated by Django 4.0.2 on 2022-06-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0004_patient_info_patient_type_patient_info_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='personal_info',
            new_name='patient_info',
        ),
        migrations.RenameField(
            model_name='next_of_kin',
            old_name='personal_info',
            new_name='patient_info',
        ),
        migrations.RenameField(
            model_name='nhisdetails',
            old_name='personal_info',
            new_name='patient_info',
        ),
        migrations.RenameField(
            model_name='openfolder',
            old_name='personal_info',
            new_name='patient_info',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='personal_info',
            new_name='patient_info',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='personal_info',
            new_name='patient_info',
        ),
        migrations.CreateModel(
            name='dependants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=120, null=True)),
                ('mname', models.CharField(blank=True, max_length=120, null=True)),
                ('lname', models.CharField(blank=True, max_length=120, null=True)),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=120, null=True)),
                ('dependant_type', models.CharField(blank=True, choices=[('s', 'SPOUSE'), ('1', 'CHILD1'), ('2', 'CHILD2'), ('3', 'CHILD3'), ('4', 'CHILD4')], max_length=10)),
                ('nhisdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordapp.nhisdetails')),
                ('patient_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
