# Generated by Django 4.0.2 on 2022-06-30 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0006_alter_patient_info_religion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependantsCivilianNHIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=120, null=True)),
                ('mname', models.CharField(blank=True, max_length=120, null=True)),
                ('lname', models.CharField(blank=True, max_length=120, null=True)),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1)),
                ('email', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=120, null=True)),
                ('dependant_type', models.CharField(blank=True, choices=[('s', 'SPOUSE'), ('1', 'CHILD1'), ('2', 'CHILD2'), ('3', 'CHILD3'), ('4', 'CHILD4')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DependantsPersonnels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=120, null=True)),
                ('mname', models.CharField(blank=True, max_length=120, null=True)),
                ('lname', models.CharField(blank=True, max_length=120, null=True)),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1)),
                ('email', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=120, null=True)),
                ('dependant_type', models.CharField(blank=True, choices=[('s', 'SPOUSE'), ('1', 'CHILD1'), ('2', 'CHILD2'), ('3', 'CHILD3'), ('4', 'CHILD4')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_No', models.CharField(blank=True, max_length=120, null=True)),
                ('name_of_service', models.CharField(blank=True, max_length=120, null=True)),
                ('rank_name', models.CharField(blank=True, max_length=120, null=True)),
                ('Command', models.CharField(blank=True, max_length=120, null=True)),
                ('presentUnit', models.TextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Personnel Record',
            },
        ),
        migrations.RemoveField(
            model_name='rank',
            name='patient_info',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='patient_info',
        ),
        migrations.AddField(
            model_name='patient_info',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='sex',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.RenameModel(
            old_name='nhisdetails',
            new_name='CivillianNHISDetails',
        ),
        migrations.DeleteModel(
            name='dependants',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AddField(
            model_name='personnel_record',
            name='patient_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info'),
        ),
        migrations.AddField(
            model_name='dependantspersonnels',
            name='nhisdetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordapp.personnel_record'),
        ),
        migrations.AddField(
            model_name='dependantspersonnels',
            name='patient_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info'),
        ),
        migrations.AddField(
            model_name='dependantsciviliannhis',
            name='nhisdetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordapp.civilliannhisdetails'),
        ),
        migrations.AddField(
            model_name='dependantsciviliannhis',
            name='patient_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info'),
        ),
    ]
