# Generated by Django 4.0.2 on 2022-06-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0007_dependantsciviliannhis_dependantspersonnels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='patient_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='religion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
